# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(151516)
$foreground = rgb(C9E2F2)
$color0 = rgb(3C3C3E)
$color1 = rgb(151221)
$color2 = rgb(14161E)
$color3 = rgb(2A4053)
$color4 = rgb(363E7E)
$color5 = rgb(416B88)
$color6 = rgb(4C80A3)
$color7 = rgb(AACCE4)
$color8 = rgb(778F9F)
$color9 = rgb(1C182C)
$color10 = rgb(1A1D28)
$color11 = rgb(38566F)
$color12 = rgb(4852A8)
$color13 = rgb(578FB6)
$color14 = rgb(66ABD9)
$color15 = rgb(AACCE4)
