# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000009)
$foreground = rgb(EBF5F6)
$color0 = rgb(000009)
$color1 = rgb(1D2E40)
$color2 = rgb(3A4628)
$color3 = rgb(405964)
$color4 = rgb(2685B1)
$color5 = rgb(9C9B33)
$color6 = rgb(95AAAB)
$color7 = rgb(DAE8E9)
$color8 = rgb(99A2A3)
$color9 = rgb(273D56)
$color10 = rgb(4D5E35)
$color11 = rgb(557685)
$color12 = rgb(32B1EC)
$color13 = rgb(D0CE44)
$color14 = rgb(C6E2E4)
$color15 = rgb(DAE8E9)
