# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EAF0F1
background         #000003
cursor             #C2AAA1

active_tab_foreground     #000003
active_tab_background     #EAF0F1
inactive_tab_foreground   #EAF0F1
inactive_tab_background   #000003

active_border_color   #EAF0F1
inactive_border_color #000003
bell_border_color     #23292E

color0      #000003
color1		#23292E
color2		#744B3D
color3		#4B595F
color4		#3A6145
color5		#447FAA
color6		#929EA2
color7		#D9E1E3
color8		#989D9F
color9		#2F363D
color10		#9B6451
color11		#64777F
color12		#4D815C
color13		#5BA9E2
color14		#C3D3D8
color15		#D9E1E3
