# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D9ECF7
background         #1E1F24
cursor             #7F8FA8

active_tab_foreground     #1E1F24
active_tab_background     #D9ECF7
inactive_tab_foreground   #D9ECF7
inactive_tab_background   #1E1F24

active_border_color   #D9ECF7
inactive_border_color #1E1F24
bell_border_color     #101729

color0      #44454A
color1		#101729
color2		#1B2544
color3		#47628E
color4		#47628E
color5		#46628F
color6		#6E96AE
color7		#C1DBEB
color8		#8799A5
color9		#161E36
color10		#24325A
color11		#5E83BE
color12		#5E83BE
color13		#5E83BE
color14		#93C8E8
color15		#C1DBEB
