# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EBF5F6
background         #000009
cursor             #9CA995

active_tab_foreground     #000009
active_tab_background     #EBF5F6
inactive_tab_foreground   #EBF5F6
inactive_tab_background   #000009

active_border_color   #EBF5F6
inactive_border_color #000009
bell_border_color     #1D2E40

color0      #000009
color1		#1D2E40
color2		#3A4628
color3		#405964
color4		#2685B1
color5		#9C9B33
color6		#95AAAB
color7		#DAE8E9
color8		#99A2A3
color9		#273D56
color10		#4D5E35
color11		#557685
color12		#32B1EC
color13		#D0CE44
color14		#C6E2E4
color15		#DAE8E9
