#!/usr/bin/env bash
# gtk-theme-gen.sh — Generate GTK CSS color overrides from matugen colors.json
# Writes to ~/.cache/matugen/gtk.css (volatile cache location).
# Called by matugen-sync.sh after colors.json is updated.
set -euo pipefail

log_info() {
    echo "[INFO] $*" >&2
}

log_error() {
    echo "[ERROR] $*" >&2
}

colors_file="$HOME/.cache/matugen/colors.json"
out_css="$HOME/.cache/matugen/gtk.css"

if [[ ! -f "$colors_file" ]]; then
    log_error "colors.json not found: $colors_file"
    exit 1
fi

if ! command -v jq > /dev/null; then
    log_error "jq is not installed"
    exit 1
fi

# Extract hex values from colors.json
primary="$(jq -r '.colors.primary' "$colors_file")"
surface="$(jq -r '.colors.surface' "$colors_file")"
background="$(jq -r '.colors.background' "$colors_file")"
surface_container="$(jq -r '.colors.surfaceContainer' "$colors_file")"
surface_container_low="$(jq -r '.colors.surfaceContainerLow' "$colors_file")"

# Validate that we got actual values (not null/empty)
for var in primary surface background surface_container surface_container_low; do
    val="${!var}"
    if [[ -z "$val" || "$val" == "null" ]]; then
        log_error "Missing color field '$var' in $colors_file"
        exit 1
    fi
done

mkdir -p "$(dirname "$out_css")"

cat > "$out_css" << EOF
/* Auto-generated by gtk-theme-gen.sh — DO NOT EDIT */
/* Re-generated on every wallpaper change via matugen-sync.sh */

@define-color accent_bg_color ${primary};
@define-color accent_color ${primary};
@define-color window_bg_color ${surface};
@define-color view_bg_color ${background};
@define-color headerbar_bg_color ${surface_container};
@define-color card_bg_color ${surface_container_low};
EOF

log_info "Wrote GTK CSS overrides to: $out_css"

# Trigger GTK color-scheme preference to force a reload in running apps
if command -v gsettings > /dev/null; then
    gsettings set org.gnome.desktop.interface color-scheme prefer-dark 2>/dev/null || true
    log_info "Toggled gsettings color-scheme to trigger GTK reload"
fi
