#!/usr/bin/env bash
# hyprlock-colors.sh
# Reads ~/.cache/matugen/colors.json and writes hyprlock variable definitions
# to ~/.cache/matugen/hyprlock-colors.conf for sourcing by hyprlock.conf.
#
# Output format (hyprlock variable syntax):
#   $lock_bg     = rgb(xxxxxx)   # surface
#   $lock_fg     = rgb(xxxxxx)   # onSurface
#   $lock_accent = rgb(xxxxxx)   # primary
#   $lock_error  = rgb(xxxxxx)   # error
#
# NOTE: Writes ONLY to the cache directory — never to the user config tree.

set -euo pipefail

log_info() { echo "[INFO] $*" >&2; }
log_warn() { echo "[WARN] $*" >&2; }
log_error() { echo "[ERROR] $*" >&2; }

cache_dir="$HOME/.cache/matugen"
colors_file="$cache_dir/colors.json"
output_file="$cache_dir/hyprlock-colors.conf"

if [[ ! -f "$colors_file" ]]; then
    log_error "colors.json not found: $colors_file"
    exit 1
fi

if ! command -v jq > /dev/null; then
    log_error "jq is not installed"
    exit 1
fi

# Strip leading '#' from hex values and format as rgb(xxxxxx)
strip_hex() {
    echo "${1#\#}"
}

surface=$(jq -r '.colors.surface // "#1e1e2e"' "$colors_file")
on_surface=$(jq -r '.colors.onSurface // "#cdd6f4"' "$colors_file")
primary=$(jq -r '.colors.primary // "#cba6f7"' "$colors_file")
error=$(jq -r '.colors.error // "#f38ba8"' "$colors_file")

lock_bg=$(strip_hex "$surface")
lock_fg=$(strip_hex "$on_surface")
lock_accent=$(strip_hex "$primary")
lock_error=$(strip_hex "$error")

mkdir -p "$cache_dir"

cat > "$output_file" <<EOF
# Auto-generated by hyprlock-colors.sh — DO NOT EDIT
# Source: $colors_file
\$lock_bg     = rgb($lock_bg)
\$lock_fg     = rgb($lock_fg)
\$lock_accent = rgb($lock_accent)
\$lock_error  = rgb($lock_error)
EOF

log_info "Wrote $output_file"
