#!/usr/bin/env bash
set -euo pipefail

log_info() {
    echo "[INFO] $*" >&2
}

log_warn() {
    echo "[WARN] $*" >&2
}

log_error() {
    echo "[ERROR] $*" >&2
}

wallpaper="${1:-}"

if [[ -z "$wallpaper" ]]; then
    log_error "Usage: $0 <wallpaper_path>"
    exit 1
fi

if [[ ! -f "$wallpaper" ]]; then
    log_error "Wallpaper not found: $wallpaper"
    exit 1
fi

if ! command -v matugen > /dev/null; then
    log_error "matugen is not installed"
    exit 1
fi

if ! command -v jq > /dev/null; then
    log_error "jq is not installed"
    exit 1
fi

cache_dir="$HOME/.cache/matugen"
colors_file="$cache_dir/colors.json"
tmp_file="$(mktemp "$cache_dir/colors.XXXXXX.json" 2>/dev/null || true)"

mkdir -p "$cache_dir"

if [[ -z "$tmp_file" ]]; then
    tmp_file="$cache_dir/colors.tmp.json"
fi

log_info "Generating Matugen palette from: $wallpaper"

matugen image "$wallpaper" --json hex \
    | jq '{
        colors: {
            primary: .colors.primary.dark,
            onPrimary: .colors.on_primary.dark,
            background: .colors.background.dark,
            onBackground: .colors.on_background.dark,
            surface: .colors.surface.dark,
            onSurface: .colors.on_surface.dark,
            surfaceVariant: .colors.surface_variant.dark,
            onSurfaceVariant: .colors.on_surface_variant.dark,
            surfaceContainer: (.colors.surface_container.dark // .colors.surface_variant.dark),
            surfaceContainerLow: (.colors.surface_container_low.dark // .colors.surface.dark),
            error: .colors.error.dark
        }
    }' > "$tmp_file"

mv "$tmp_file" "$colors_file"
log_info "Wrote $colors_file"

# Generate GTK CSS overrides from the new colors.json
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
gtk_gen="$script_dir/gtk-theme-gen.sh"
if [[ -x "$gtk_gen" ]]; then
    log_info "Generating GTK CSS overrides..."
    "$gtk_gen" || log_warn "gtk-theme-gen.sh failed (non-fatal)"
else
    log_warn "gtk-theme-gen.sh not found or not executable: $gtk_gen"
fi

# Generate hyprlock color variables from the new colors.json
hyprlock_gen="$script_dir/hyprlock-colors.sh"
if [[ -x "$hyprlock_gen" ]]; then
    log_info "Generating hyprlock color variables..."
    "$hyprlock_gen" || log_warn "hyprlock-colors.sh failed (non-fatal)"
else
    log_warn "hyprlock-colors.sh not found or not executable: $hyprlock_gen"
fi

# Shared color values for downstream app theme files
primary="$(jq -r '.colors.primary // "#cba6f7"' "$colors_file")"
on_primary="$(jq -r '.colors.onPrimary // "#11111b"' "$colors_file")"
background="$(jq -r '.colors.background // "#1e1e2e"' "$colors_file")"
on_background="$(jq -r '.colors.onBackground // "#cdd6f4"' "$colors_file")"
surface="$(jq -r '.colors.surface // "#313244"' "$colors_file")"
on_surface="$(jq -r '.colors.onSurface // "#cdd6f4"' "$colors_file")"
surface_variant="$(jq -r '.colors.surfaceVariant // "#45475a"' "$colors_file")"
error="$(jq -r '.colors.error // "#f38ba8"' "$colors_file")"

# Generate Ghostty include config (loaded from ~/.cache/matugen/ghostty.conf)
ghostty_out="$cache_dir/ghostty.conf"
cat > "$ghostty_out" <<EOF
# Auto-generated by matugen-sync.sh — DO NOT EDIT
background = ${background}
foreground = ${on_surface}
cursor-color = ${primary}
selection-background = ${surface_variant}
selection-foreground = ${on_surface}
palette = 0=${surface}
palette = 1=${error}
palette = 2=${primary}
palette = 3=${on_primary}
palette = 4=${primary}
palette = 5=${surface_variant}
palette = 6=${on_background}
palette = 7=${on_surface}
palette = 8=${surface_variant}
palette = 9=${error}
palette = 10=${primary}
palette = 11=${on_primary}
palette = 12=${primary}
palette = 13=${surface_variant}
palette = 14=${on_background}
palette = 15=${on_surface}
EOF
log_info "Wrote Ghostty include: $ghostty_out"

# Generate Zsh color exports for interactive tools (sourced in ~/.zshrc)
zsh_out="$cache_dir/zsh-colors.zsh"
cat > "$zsh_out" <<EOF
# Auto-generated by matugen-sync.sh — DO NOT EDIT
export MATUGEN_PRIMARY='${primary}'
export MATUGEN_ON_PRIMARY='${on_primary}'
export MATUGEN_BACKGROUND='${background}'
export MATUGEN_ON_BACKGROUND='${on_background}'
export MATUGEN_SURFACE='${surface}'
export MATUGEN_ON_SURFACE='${on_surface}'
export MATUGEN_SURFACE_VARIANT='${surface_variant}'
export MATUGEN_ERROR='${error}'
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=${surface_variant}'
_matugen_fzf_colors='--color=bg+:-1,bg:${background},fg:${on_surface},hl:${primary},hl+:${primary},info:${primary},prompt:${primary},pointer:${primary},marker:${primary},spinner:${primary},header:${primary}'
if [[ -n "\${FZF_DEFAULT_OPTS:-}" ]]; then
  export FZF_DEFAULT_OPTS="\${FZF_DEFAULT_OPTS} \${_matugen_fzf_colors}"
else
  export FZF_DEFAULT_OPTS="\${_matugen_fzf_colors}"
fi
unset _matugen_fzf_colors
EOF
log_info "Wrote Zsh color exports: $zsh_out"

# Generate Starship config with Matugen palette (loaded via STARSHIP_CONFIG)
starship_out="$cache_dir/starship.toml"
cat > "$starship_out" <<EOF
# Auto-generated by matugen-sync.sh — DO NOT EDIT
palette = "matugen"

format = """
\$username\
\$hostname\
\$directory\
\$git_branch\
\$git_status\
\$nodejs\
\$python\
\$rust\
\$docker_context\
\$cmd_duration\
\$line_break\
\$character"""

[character]
success_symbol = "[❯](bold primary)"
error_symbol = "[❯](bold error)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold primary"

[git_branch]
symbol = " "
format = "on [\$symbol\$branch](\$style) "
style = "primary"

[git_status]
format = '([\$all_status\$ahead_behind](\$style) )'
style = "muted"

[nodejs]
symbol = " "
format = "via [\$symbol(\$version )](\$style)"
style = "muted"

[python]
symbol = " "
format = 'via [\${symbol}\${pyenv_prefix}(\${version} )(\(\$virtualenv\) )](\$style)'
style = "muted"

[rust]
symbol = " "
format = "via [\$symbol(\$version )](\$style)"
style = "muted"

[docker_context]
symbol = " "
format = "via [\$symbol\$context](\$style) "
style = "muted"

[cmd_duration]
min_time = 2_000
format = "took [\$duration](\$style) "
style = "muted"

[palettes.matugen]
primary = "${primary}"
text = "${on_surface}"
muted = "${surface_variant}"
bg = "${background}"
error = "${error}"
accent = "${on_primary}"
EOF
log_info "Wrote Starship config: $starship_out"

# No IPC needed — GlobalState.qml uses a FileWatcher on colors.json
# which detects this write and triggers reloadColors() automatically.
log_info "FileWatcher will pick up the change automatically"
