[config]
reload_apps = true
# Use matugen to generate Quickshell color configs
[templates.quickshell]
input_path = "~/.config/quickshell/assets/matugen/qs_colors.json.tpl"
output_path = "~/.cache/matugen/colors.json"
