# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = thunar
$terminal = ghostty
$browser = firefox
$musicplayer = spotify

# Quickshell IPC commands
$applauncher    = qs ipc call toggle-launcher toggle
$powermenu      = qs ipc call toggle-power toggle
$quicksettings  = qs ipc call toggle-control-center toggle
$wallpapers     = qs ipc call toggle-wallpapers toggle

# Screenshots
$shot-region = grimblast copy area
$shot-window = grimblast copy active
$shot-screen = grimblast copy output
